
package ru.kuznetsov.service.CBRClasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditOrgInfoSoap", targetNamespace = "http://web.cbr.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditOrgInfoSoap {


    /**
     * Данные по BIC кодам КО (как XMLDocument), без
     *         филиалов, ver: 04.07.2007
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.EnumBICXMLResponse.EnumBICXMLResult
     */
    @WebMethod(operationName = "EnumBIC_XML", action = "http://web.cbr.ru/EnumBIC_XML")
    @WebResult(name = "EnumBIC_XMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumBIC_XML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.EnumBICXML")
    @ResponseWrapper(localName = "EnumBIC_XMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.EnumBICXMLResponse")
    public ru.kuznetsov.service.CBRClasses.EnumBICXMLResponse.EnumBICXMLResult enumBICXML();

    /**
     * Получение максимальной даты отчетов по формам,
     *         ver: 22.04.2015
     *       
     * 
     * @param code
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetFormsMaxDate", action = "http://web.cbr.ru/GetFormsMaxDate")
    @WebResult(name = "GetFormsMaxDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetFormsMaxDate", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetFormsMaxDate")
    @ResponseWrapper(localName = "GetFormsMaxDateResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetFormsMaxDateResponse")
    public XMLGregorianCalendar getFormsMaxDate(
        @WebParam(name = "code", targetNamespace = "http://web.cbr.ru/")
        int code);

    /**
     * Получение даты последнего обновления базы по
     *         КО
     *       
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "LastUpdate", action = "http://web.cbr.ru/LastUpdate")
    @WebResult(name = "LastUpdateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "LastUpdate", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.LastUpdate")
    @ResponseWrapper(localName = "LastUpdateResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.LastUpdateResponse")
    public XMLGregorianCalendar lastUpdate();

    /**
     * Данные по BIC кодам КО (как DataSet), без
     *         филиалов, ver: 17.03.2015
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.EnumBICResponse.EnumBICResult
     */
    @WebMethod(operationName = "EnumBIC", action = "http://web.cbr.ru/EnumBIC")
    @WebResult(name = "EnumBICResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumBIC", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.EnumBIC")
    @ResponseWrapper(localName = "EnumBICResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.EnumBICResponse")
    public ru.kuznetsov.service.CBRClasses.EnumBICResponse.EnumBICResult enumBIC();

    /**
     * Данные КО. формы 101 (как XMLDocument) по
     *         нескольким КО
     *       
     * 
     * @param indID
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FormExXMLResponse.Data101FormExXMLResult
     */
    @WebMethod(operationName = "Data101FormExXML", action = "http://web.cbr.ru/Data101FormExXML")
    @WebResult(name = "Data101FormExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FormExXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormExXML")
    @ResponseWrapper(localName = "Data101FormExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormExXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FormExXMLResponse.Data101FormExXMLResult data101FormExXML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
        int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101, без оборотов (как DataSet)
     *         по нескольким КО ver 07.03.2017
     *       
     * 
     * @param indID
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FormExResponse.Data101FormExResult
     */
    @WebMethod(operationName = "Data101FormEx", action = "http://web.cbr.ru/Data101FormEx")
    @WebResult(name = "Data101FormExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FormEx", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormEx")
    @ResponseWrapper(localName = "Data101FormExResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormExResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FormExResponse.Data101FormExResult data101FormEx(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
        int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101, без оборотов (как
     *         XMLDocument)
     *       
     * 
     * @param indID
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FormXMLResponse.Data101FormXMLResult
     */
    @WebMethod(operationName = "Data101FormXML", action = "http://web.cbr.ru/Data101FormXML")
    @WebResult(name = "Data101FormXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FormXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormXML")
    @ResponseWrapper(localName = "Data101FormXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FormXMLResponse.Data101FormXMLResult data101FormXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
        int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101, без оборотов (как
     *         DataSet)
     *       
     * 
     * @param indID
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FormResponse.Data101FormResult
     */
    @WebMethod(operationName = "Data101Form", action = "http://web.cbr.ru/Data101Form")
    @WebResult(name = "Data101FormResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101Form", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101Form")
    @ResponseWrapper(localName = "Data101FormResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FormResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FormResponse.Data101FormResult data101Form(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
        int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101, полностью (как
     *         XMLDocument)
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullXMLResponse.Data101FullXMLResult
     */
    @WebMethod(operationName = "Data101FullXML", action = "http://web.cbr.ru/Data101FullXML")
    @WebResult(name = "Data101FullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullXML")
    @ResponseWrapper(localName = "Data101FullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FullXMLResponse.Data101FullXMLResult data101FullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (Внимание, метод
     *         устарел, используйте v2) (как XMLDocument) по нескольким КО. ver 17.03.2015
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullExXMLResponse.Data101FullExXMLResult
     */
    @WebMethod(operationName = "Data101FullExXML", action = "http://web.cbr.ru/Data101FullExXML")
    @WebResult(name = "Data101FullExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullExXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExXML")
    @ResponseWrapper(localName = "Data101FullExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FullExXMLResponse.Data101FullExXMLResult data101FullExXML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (Внимание, метод
     *         устарел, используйте v2) (как DataSet) ver 17.03.2015
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullExResponse.Data101FullExResult
     */
    @WebMethod(operationName = "Data101FullEx", action = "http://web.cbr.ru/Data101FullEx")
    @WebResult(name = "Data101FullExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullEx", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullEx")
    @ResponseWrapper(localName = "Data101FullExResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FullExResponse.Data101FullExResult data101FullEx(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (как XML) ver
     *         07.03.2017
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullExV2XMLResponse.Data101FullExV2XMLResult
     */
    @WebMethod(operationName = "Data101FullExV2XML", action = "http://web.cbr.ru/Data101FullExV2XML")
    @WebResult(name = "Data101FullExV2XMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullExV2XML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExV2XML")
    @ResponseWrapper(localName = "Data101FullExV2XMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExV2XMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FullExV2XMLResponse.Data101FullExV2XMLResult data101FullExV2XML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (как DataSet) ver
     *         07.03.2017
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullExV2Response.Data101FullExV2Result
     */
    @WebMethod(operationName = "Data101FullExV2", action = "http://web.cbr.ru/Data101FullExV2")
    @WebResult(name = "Data101FullExV2Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullExV2", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExV2")
    @ResponseWrapper(localName = "Data101FullExV2Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullExV2Response")
    public ru.kuznetsov.service.CBRClasses.Data101FullExV2Response.Data101FullExV2Result data101FullExV2(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (Устарел,
     *         используйте v2) (как DataSet)
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullResponse.Data101FullResult
     */
    @WebMethod(operationName = "Data101Full", action = "http://web.cbr.ru/Data101Full")
    @WebResult(name = "Data101FullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101Full", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101Full")
    @ResponseWrapper(localName = "Data101FullResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FullResponse.Data101FullResult data101Full(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (как XML) mod
     *         07.03.2017
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullV2XMLResponse.Data101FullV2XMLResult
     */
    @WebMethod(operationName = "Data101FullV2XML", action = "http://web.cbr.ru/Data101FullV2XML")
    @WebResult(name = "Data101FullV2XMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullV2XML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullV2XML")
    @ResponseWrapper(localName = "Data101FullV2XMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullV2XMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data101FullV2XMLResponse.Data101FullV2XMLResult data101FullV2XML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 101,полностью (как DataSet) mod
     *         07.03.2017
     *       
     * 
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data101FullV2Response.Data101FullV2Result
     */
    @WebMethod(operationName = "Data101FullV2", action = "http://web.cbr.ru/Data101FullV2")
    @WebResult(name = "Data101FullV2Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullV2", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullV2")
    @ResponseWrapper(localName = "Data101FullV2Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data101FullV2Response")
    public ru.kuznetsov.service.CBRClasses.Data101FullV2Response.Data101FullV2Result data101FullV2(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
        String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 102, кратко (как XMLDocument)
     *         по нескольким КО.
     *       
     * 
     * @param symbCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data102FormExXMLResponse.Data102FormExXMLResult
     */
    @WebMethod(operationName = "Data102FormExXML", action = "http://web.cbr.ru/Data102FormExXML")
    @WebResult(name = "Data102FormExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102FormExXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormExXML")
    @ResponseWrapper(localName = "Data102FormExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormExXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data102FormExXMLResponse.Data102FormExXMLResult data102FormExXML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
        int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 102 (как DataSet) по нескольким
     *         КО. ver 24.06.2014
     *       
     * 
     * @param symbCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data102FormExResponse.Data102FormExResult
     */
    @WebMethod(operationName = "Data102FormEx", action = "http://web.cbr.ru/Data102FormEx")
    @WebResult(name = "Data102FormExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102FormEx", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormEx")
    @ResponseWrapper(localName = "Data102FormExResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormExResponse")
    public ru.kuznetsov.service.CBRClasses.Data102FormExResponse.Data102FormExResult data102FormEx(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
        ArrayOfAnyType credorgNumbers,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
        int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 102, кратко (как XMLDocument)
     *       
     * 
     * @param symbCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data102FormXMLResponse.Data102FormXMLResult
     */
    @WebMethod(operationName = "Data102FormXML", action = "http://web.cbr.ru/Data102FormXML")
    @WebResult(name = "Data102FormXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102FormXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormXML")
    @ResponseWrapper(localName = "Data102FormXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data102FormXMLResponse.Data102FormXMLResult data102FormXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
        int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Данные КО. формы 102 (как DataSet)
     *       
     * 
     * @param symbCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data102FormResponse.Data102FormResult
     */
    @WebMethod(operationName = "Data102Form", action = "http://web.cbr.ru/Data102Form")
    @WebResult(name = "Data102FormResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102Form", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102Form")
    @ResponseWrapper(localName = "Data102FormResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data102FormResponse")
    public ru.kuznetsov.service.CBRClasses.Data102FormResponse.Data102FormResult data102Form(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
        int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar dateTo);

    /**
     * Справочник символов для формы 102 (как
     *         XMLDocument)
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult
     */
    @WebMethod(operationName = "Form102IndicatorsEnumXML", action = "http://web.cbr.ru/Form102IndicatorsEnumXML")
    @WebResult(name = "Form102IndicatorsEnumXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form102IndicatorsEnumXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumXML")
    @ResponseWrapper(localName = "Form102IndicatorsEnumXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult form102IndicatorsEnumXML();

    /**
     * Справочник символов для формы 102 (как
     *         DataSet)
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult
     */
    @WebMethod(operationName = "Form102IndicatorsEnum", action = "http://web.cbr.ru/Form102IndicatorsEnum")
    @WebResult(name = "Form102IndicatorsEnumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form102IndicatorsEnum", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnum")
    @ResponseWrapper(localName = "Form102IndicatorsEnumResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumResponse")
    public ru.kuznetsov.service.CBRClasses.Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult form102IndicatorsEnum();

    /**
     * Справочник индикаторов для формы 101 (как
     *         XMLDocument)
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult
     */
    @WebMethod(operationName = "Form101IndicatorsEnumXML", action = "http://web.cbr.ru/Form101IndicatorsEnumXML")
    @WebResult(name = "Form101IndicatorsEnumXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form101IndicatorsEnumXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumXML")
    @ResponseWrapper(localName = "Form101IndicatorsEnumXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult form101IndicatorsEnumXML();

    /**
     * Справочник индикаторов для формы 101 (как
     *         DataSet)
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult
     */
    @WebMethod(operationName = "Form101IndicatorsEnum", action = "http://web.cbr.ru/Form101IndicatorsEnum")
    @WebResult(name = "Form101IndicatorsEnumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form101IndicatorsEnum", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnum")
    @ResponseWrapper(localName = "Form101IndicatorsEnumResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumResponse")
    public ru.kuznetsov.service.CBRClasses.Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult form101IndicatorsEnum();

    /**
     * Регистрационный номер во внутренний код КО.
     *       
     * 
     * @param regNumber
     * @return
     *     returns double
     */
    @WebMethod(operationName = "RegNumToIntCode", action = "http://web.cbr.ru/RegNumToIntCode")
    @WebResult(name = "RegNumToIntCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RegNumToIntCode", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.RegNumToIntCode")
    @ResponseWrapper(localName = "RegNumToIntCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.RegNumToIntCodeResponse")
    public double regNumToIntCode(
        @WebParam(name = "RegNumber", targetNamespace = "http://web.cbr.ru/")
        double regNumber);

    /**
     * внутренний код кред.орг. в регистрационный номер
     *         КО.
     *       
     * 
     * @param intNumber
     * @return
     *     returns double
     */
    @WebMethod(operationName = "IntCodeToRegNum", action = "http://web.cbr.ru/IntCodeToRegNum")
    @WebResult(name = "IntCodeToRegNumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "IntCodeToRegNum", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.IntCodeToRegNum")
    @ResponseWrapper(localName = "IntCodeToRegNumResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.IntCodeToRegNumResponse")
    public double intCodeToRegNum(
        @WebParam(name = "IntNumber", targetNamespace = "http://web.cbr.ru/")
        double intNumber);

    /**
     * Bic код во внутренний код кред.орг.
     *       
     * 
     * @param bicCode
     * @return
     *     returns double
     */
    @WebMethod(operationName = "BicToIntCode", action = "http://web.cbr.ru/BicToIntCode")
    @WebResult(name = "BicToIntCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BicToIntCode", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.BicToIntCode")
    @ResponseWrapper(localName = "BicToIntCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.BicToIntCodeResponse")
    public double bicToIntCode(
        @WebParam(name = "BicCode", targetNamespace = "http://web.cbr.ru/")
        String bicCode);

    /**
     * Bic код в регистрационный номер кред.орг.
     *       
     * 
     * @param bicCode
     * @return
     *     returns int
     */
    @WebMethod(operationName = "BicToRegNumber", action = "http://web.cbr.ru/BicToRegNumber")
    @WebResult(name = "BicToRegNumberResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BicToRegNumber", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.BicToRegNumber")
    @ResponseWrapper(localName = "BicToRegNumberResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.BicToRegNumberResponse")
    public int bicToRegNumber(
        @WebParam(name = "BicCode", targetNamespace = "http://web.cbr.ru/")
        String bicCode);

    /**
     * Справочник регионов (как DataSet)
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.RegionsEnumResponse.RegionsEnumResult
     */
    @WebMethod(operationName = "RegionsEnum", action = "http://web.cbr.ru/RegionsEnum")
    @WebResult(name = "RegionsEnumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RegionsEnum", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.RegionsEnum")
    @ResponseWrapper(localName = "RegionsEnumResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.RegionsEnumResponse")
    public ru.kuznetsov.service.CBRClasses.RegionsEnumResponse.RegionsEnumResult regionsEnum();

    /**
     * Справочник регионов (как XMLDocument), ver-
     *         18.01.2007
     *       
     * 
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.RegionsEnumXMLResponse.RegionsEnumXMLResult
     */
    @WebMethod(operationName = "RegionsEnumXML", action = "http://web.cbr.ru/RegionsEnumXML")
    @WebResult(name = "RegionsEnumXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RegionsEnumXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.RegionsEnumXML")
    @ResponseWrapper(localName = "RegionsEnumXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.RegionsEnumXMLResponse")
    public ru.kuznetsov.service.CBRClasses.RegionsEnumXMLResponse.RegionsEnumXMLResult regionsEnumXML();

    /**
     * Поиск кредитных орг. по региону(коду) (как
     *         DataSet)
     *       
     * 
     * @param regCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.SearchByRegionCodeResponse.SearchByRegionCodeResult
     */
    @WebMethod(operationName = "SearchByRegionCode", action = "http://web.cbr.ru/SearchByRegionCode")
    @WebResult(name = "SearchByRegionCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByRegionCode", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByRegionCode")
    @ResponseWrapper(localName = "SearchByRegionCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByRegionCodeResponse")
    public ru.kuznetsov.service.CBRClasses.SearchByRegionCodeResponse.SearchByRegionCodeResult searchByRegionCode(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
        int regCode);

    /**
     * Поиск кредитных орг. по региону(коду) (как
     *         XML)
     *       
     * 
     * @param regCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult
     */
    @WebMethod(operationName = "SearchByRegionCodeXML", action = "http://web.cbr.ru/SearchByRegionCodeXML")
    @WebResult(name = "SearchByRegionCodeXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByRegionCodeXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByRegionCodeXML")
    @ResponseWrapper(localName = "SearchByRegionCodeXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByRegionCodeXMLResponse")
    public ru.kuznetsov.service.CBRClasses.SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult searchByRegionCodeXML(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
        int regCode);

    /**
     * Поиск кредитных орг. по названию (как XML)
     *       
     * 
     * @param namePart
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.SearchByNameXMLResponse.SearchByNameXMLResult
     */
    @WebMethod(operationName = "SearchByNameXML", action = "http://web.cbr.ru/SearchByNameXML")
    @WebResult(name = "SearchByNameXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByNameXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByNameXML")
    @ResponseWrapper(localName = "SearchByNameXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByNameXMLResponse")
    public ru.kuznetsov.service.CBRClasses.SearchByNameXMLResponse.SearchByNameXMLResult searchByNameXML(
        @WebParam(name = "NamePart", targetNamespace = "http://web.cbr.ru/")
        String namePart);

    /**
     * Поиск кредитных орг. по названию (как DataSet)
     *       
     * 
     * @param namePart
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.SearchByNameResponse.SearchByNameResult
     */
    @WebMethod(operationName = "SearchByName", action = "http://web.cbr.ru/SearchByName")
    @WebResult(name = "SearchByNameResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByName", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByName")
    @ResponseWrapper(localName = "SearchByNameResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.SearchByNameResponse")
    public ru.kuznetsov.service.CBRClasses.SearchByNameResponse.SearchByNameResult searchByName(
        @WebParam(name = "NamePart", targetNamespace = "http://web.cbr.ru/")
        String namePart);

    /**
     * Информация о кредитной орг. по вн.коду (как
     *         XMLDocument)
     *       
     * 
     * @param internalCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult
     */
    @WebMethod(operationName = "CreditInfoByIntCodeXML", action = "http://web.cbr.ru/CreditInfoByIntCodeXML")
    @WebResult(name = "CreditInfoByIntCodeXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCodeXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeXML")
    @ResponseWrapper(localName = "CreditInfoByIntCodeXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeXMLResponse")
    public ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult creditInfoByIntCodeXML(
        @WebParam(name = "InternalCode", targetNamespace = "http://web.cbr.ru/")
        double internalCode);

    /**
     * Информация о кредитной орг. по вн.коду (как XML
     *         Document) ver- 26.02.2015
     *       
     * 
     * @param internalCodes
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult
     */
    @WebMethod(operationName = "CreditInfoByIntCodeExXML", action = "http://web.cbr.ru/CreditInfoByIntCodeExXML")
    @WebResult(name = "CreditInfoByIntCodeExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCodeExXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExXML")
    @ResponseWrapper(localName = "CreditInfoByIntCodeExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExXMLResponse")
    public ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult creditInfoByIntCodeExXML(
        @WebParam(name = "InternalCodes", targetNamespace = "http://web.cbr.ru/")
        ArrayOfDouble internalCodes);

    /**
     * Информация о кредитной орг. по вн.коду (как
     *         DataSet) ver- 03.03.2015
     *       
     * 
     * @param internalCodes
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult
     */
    @WebMethod(operationName = "CreditInfoByIntCodeEx", action = "http://web.cbr.ru/CreditInfoByIntCodeEx")
    @WebResult(name = "CreditInfoByIntCodeExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCodeEx", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeEx")
    @ResponseWrapper(localName = "CreditInfoByIntCodeExResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExResponse")
    public ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult creditInfoByIntCodeEx(
        @WebParam(name = "InternalCodes", targetNamespace = "http://web.cbr.ru/")
        ArrayOfDouble internalCodes);

    /**
     * Информация о кредитной орг. по вн.коду (как
     *         DataSet) ver- 11.01.2007
     *       
     * 
     * @param internalCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult
     */
    @WebMethod(operationName = "CreditInfoByIntCode", action = "http://web.cbr.ru/CreditInfoByIntCode")
    @WebResult(name = "CreditInfoByIntCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCode", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCode")
    @ResponseWrapper(localName = "CreditInfoByIntCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeResponse")
    public ru.kuznetsov.service.CBRClasses.CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult creditInfoByIntCode(
        @WebParam(name = "InternalCode", targetNamespace = "http://web.cbr.ru/")
        double internalCode);

    /**
     * Информация по филиальной сети кредитной орг. по
     *         вн.коду (как DataSet), ver- 18.01.2007
     *       
     * 
     * @param intCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.GetOfficesResponse.GetOfficesResult
     */
    @WebMethod(operationName = "GetOffices", action = "http://web.cbr.ru/GetOffices")
    @WebResult(name = "GetOfficesResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOffices", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOffices")
    @ResponseWrapper(localName = "GetOfficesResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesResponse")
    public ru.kuznetsov.service.CBRClasses.GetOfficesResponse.GetOfficesResult getOffices(
        @WebParam(name = "IntCode", targetNamespace = "http://web.cbr.ru/")
        double intCode);

    /**
     * Информация по филиальной сети кредитной орг. по
     *         региону (коду) (как DataSet), ver- 18.01.2007
     *       
     * 
     * @param regCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.GetOfficesByRegionResponse.GetOfficesByRegionResult
     */
    @WebMethod(operationName = "GetOfficesByRegion", action = "http://web.cbr.ru/GetOfficesByRegion")
    @WebResult(name = "GetOfficesByRegionResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOfficesByRegion", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesByRegion")
    @ResponseWrapper(localName = "GetOfficesByRegionResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesByRegionResponse")
    public ru.kuznetsov.service.CBRClasses.GetOfficesByRegionResponse.GetOfficesByRegionResult getOfficesByRegion(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
        int regCode);

    /**
     * Информация по филиальной сети кредитной орг. по
     *         вн.коду (как XML)
     *       
     * 
     * @param intCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.GetOfficesXMLResponse.GetOfficesXMLResult
     */
    @WebMethod(operationName = "GetOfficesXML", action = "http://web.cbr.ru/GetOfficesXML")
    @WebResult(name = "GetOfficesXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOfficesXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesXML")
    @ResponseWrapper(localName = "GetOfficesXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesXMLResponse")
    public ru.kuznetsov.service.CBRClasses.GetOfficesXMLResponse.GetOfficesXMLResult getOfficesXML(
        @WebParam(name = "IntCode", targetNamespace = "http://web.cbr.ru/")
        double intCode);

    /**
     * Информация по филиальной сети кредитной орг. по
     *         региону (коду) (как XML), ver- 18.01.2007
     *       
     * 
     * @param regCode
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult
     */
    @WebMethod(operationName = "GetOfficesByRegionXML", action = "http://web.cbr.ru/GetOfficesByRegionXML")
    @WebResult(name = "GetOfficesByRegionXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOfficesByRegionXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesByRegionXML")
    @ResponseWrapper(localName = "GetOfficesByRegionXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetOfficesByRegionXMLResponse")
    public ru.kuznetsov.service.CBRClasses.GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult getOfficesByRegionXML(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
        int regCode);

    /**
     * Данные по форме 134 (как XML)
     *       
     * 
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data134FormFullXMLResponse.Data134FormFullXMLResult
     */
    @WebMethod(operationName = "Data134FormFullXML", action = "http://web.cbr.ru/Data134FormFullXML")
    @WebResult(name = "Data134FormFullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data134FormFullXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data134FormFullXML")
    @ResponseWrapper(localName = "Data134FormFullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data134FormFullXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data134FormFullXMLResponse.Data134FormFullXMLResult data134FormFullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Данные по форме 134, OLAP, (как DataSet)
     *       
     * 
     * @param fromDate
     * @param code
     * @param toDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Olap134FormResponse.Olap134FormResult
     */
    @WebMethod(operationName = "Olap134Form", action = "http://web.cbr.ru/Olap134Form")
    @WebResult(name = "Olap134FormResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Olap134Form", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Olap134Form")
    @ResponseWrapper(localName = "Olap134FormResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Olap134FormResponse")
    public ru.kuznetsov.service.CBRClasses.Olap134FormResponse.Olap134FormResult olap134Form(
        @WebParam(name = "Code", targetNamespace = "http://web.cbr.ru/")
        String code,
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar toDate);

    /**
     * Данные по форме 135 (как DataSet) ver
     *         05.06.2014
     *       
     * 
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data135FormFullResponse.Data135FormFullResult
     */
    @WebMethod(operationName = "Data135FormFull", action = "http://web.cbr.ru/Data135FormFull")
    @WebResult(name = "Data135FormFullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data135FormFull", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data135FormFull")
    @ResponseWrapper(localName = "Data135FormFullResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data135FormFullResponse")
    public ru.kuznetsov.service.CBRClasses.Data135FormFullResponse.Data135FormFullResult data135FormFull(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Данные по форме 135 (как XML)
     *       
     * 
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data135FormFullXMLResponse.Data135FormFullXMLResult
     */
    @WebMethod(operationName = "Data135FormFullXML", action = "http://web.cbr.ru/Data135FormFullXML")
    @WebResult(name = "Data135FormFullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data135FormFullXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data135FormFullXML")
    @ResponseWrapper(localName = "Data135FormFullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data135FormFullXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data135FormFullXMLResponse.Data135FormFullXMLResult data135FormFullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Данные по форме 123 (как DataSet)
     *       
     * 
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data123FormFullResponse.Data123FormFullResult
     */
    @WebMethod(operationName = "Data123FormFull", action = "http://web.cbr.ru/Data123FormFull")
    @WebResult(name = "Data123FormFullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data123FormFull", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data123FormFull")
    @ResponseWrapper(localName = "Data123FormFullResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data123FormFullResponse")
    public ru.kuznetsov.service.CBRClasses.Data123FormFullResponse.Data123FormFullResult data123FormFull(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Данные по форме 123 (как XML)
     *       
     * 
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data123FormFullXMLResponse.Data123FormFullXMLResult
     */
    @WebMethod(operationName = "Data123FormFullXML", action = "http://web.cbr.ru/Data123FormFullXML")
    @WebResult(name = "Data123FormFullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data123FormFullXML", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data123FormFullXML")
    @ResponseWrapper(localName = "Data123FormFullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data123FormFullXMLResponse")
    public ru.kuznetsov.service.CBRClasses.Data123FormFullXMLResponse.Data123FormFullXMLResult data123FormFullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

    /**
     * Список дат для формы 123
     * 
     * @param credprgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF123", action = "http://web.cbr.ru/GetDatesForF123")
    @WebResult(name = "GetDatesForF123Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF123", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF123")
    @ResponseWrapper(localName = "GetDatesForF123Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF123Response")
    public ArrayOfDateTime getDatesForF123(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
        int credprgNumber);

    /**
     * Список дат для формы 101
     * 
     * @param credprgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF101", action = "http://web.cbr.ru/GetDatesForF101")
    @WebResult(name = "GetDatesForF101Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF101", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF101")
    @ResponseWrapper(localName = "GetDatesForF101Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF101Response")
    public ArrayOfDateTime getDatesForF101(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
        int credprgNumber);

    /**
     * Список дат для формы 102
     * 
     * @param credprgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF102", action = "http://web.cbr.ru/GetDatesForF102")
    @WebResult(name = "GetDatesForF102Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF102", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF102")
    @ResponseWrapper(localName = "GetDatesForF102Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF102Response")
    public ArrayOfDateTime getDatesForF102(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
        int credprgNumber);

    /**
     * Список дат для формы 134
     * 
     * @param credprgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF134", action = "http://web.cbr.ru/GetDatesForF134")
    @WebResult(name = "GetDatesForF134Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF134", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF134")
    @ResponseWrapper(localName = "GetDatesForF134Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF134Response")
    public ArrayOfDateTime getDatesForF134(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
        int credprgNumber);

    /**
     * Список дат для формы 135
     * 
     * @param credprgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF135", action = "http://web.cbr.ru/GetDatesForF135")
    @WebResult(name = "GetDatesForF135Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF135", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF135")
    @ResponseWrapper(localName = "GetDatesForF135Response", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.GetDatesForF135Response")
    public ArrayOfDateTime getDatesForF135(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
        int credprgNumber);

    /**
     * Данные по форме 134 - устаревшие, данные до 2015
     *         г. (как DataSet)
     *       
     * 
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns ru.kuznetsov.service.CBRClasses.Data134FormFullResponse.Data134FormFullResult
     */
    @WebMethod(operationName = "Data134FormFull", action = "http://web.cbr.ru/Data134FormFull")
    @WebResult(name = "Data134FormFullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data134FormFull", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data134FormFull")
    @ResponseWrapper(localName = "Data134FormFullResponse", targetNamespace = "http://web.cbr.ru/", className = "ru.kuznetsov.service.CBRClasses.Data134FormFullResponse")
    public ru.kuznetsov.service.CBRClasses.Data134FormFullResponse.Data134FormFullResult data134FormFull(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
        int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
        XMLGregorianCalendar onDate);

}
